import type { Metadata } from "next";
import { Geist, Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
// import { AuthProvider } from "@/context/AuthContext";
// import { AuthProvider } from "@/context/AuthContext";
// import Footer from "@/components/Footer";

// Configure fonts
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"], weight: ["400", "800"] });

// Metadata for the app
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${inter.className} antialiased bg-white min-h-screen`}>
				{/* Main content */}

				<main className='w-full px-[15px] md:mx-auto max-w-[1512px] xl:px-[79px]'>
					<AuthProvider>{children}</AuthProvider>
				</main>
				{/* <Footer /> */}
			</body>
		</html>
	);
}
