import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import { AuthProvider } from "@/context/AuthContext";
// import { BasketProvider } from "@/context/BasketContext";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"], weight: ["400", "800"] });

// Metadata for the app
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.className} antialiased bg-white min-h-screen`}>
				<main>
					<Providers>{children}</Providers>
				</main>
			</body>
		</html>
	);
}
